name: Docker Hub push action

on:
  push:
    branches: ["master"]
    
jobs:
  build_and_push:
    runs-on: ubuntu:latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Build Docker Image
        run: docker build . --file Dockerfile -t heiwalocal/ms1:latest
      
      - name: Login into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Push tag to Docker Hub
        run: docker push heiwalocal/ms1:latest
